install.packages("ggplot2")
install.packages("rmarkdown")
install.packages("dplyr")
install.packages("evaluate")
install.packages("digest")
install.packages("highr")
install.packages("markdown")
install.packages("stringr")
install.packages("yaml")
install.packages("Rcpp")
install.packages("htmltools")
install.packages("caTools")
install.packages("bitops")
install.packages("knitr")
install.packages("jsonlite")
install.packages("base64enc")
install.packages("rprojroot")

